
name: Release new version

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-ghpkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
